version: "3"
services:
  app:
    build: .
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - .:/src
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: dockerExpressDemo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
